version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`portainer.seudominio.com`)" # Substitua pelo seu domínio
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls.certresolver=myresolver"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - portainer-net
    ports:
      - 9443:9443 # use 9000 para HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Necessário para gerenciar o Docker host
      - portainer_data:/data

volumes:
  portainer_data:

networks:
  portainer-net:
    external: true
